# Conclusion

Throughout this project we were able to address all of our initial research questions. We saw that there were, in fact, two distinct spikes for two categories of opioids as the CDC claimed. Heroin and synthetics saw dramatic rises in overdoses in the years 2010 and 2013, respectively. There were small discernible differences in the rates at which different ethnic groups were afflicted, but the opioid crisis is an omnipresent issue for all races. We found that men are proportionally more likely to fall victim to a fatal overdose than women, with the exception of the American Indian/Alaska Native group, which saw equal rates for both genders. As a whole, heroin and synthetic opioids have caused a devastating number of overdoses in recent years, but natural/semisynthetic opioids have been constantly problematic for two decades. 
Age does play a role in overdose trends, with most overdoses occurring in the middle-aged population. Heroin and synthetics have been the main cause of overdose for younger populations, while methodone and natural/semisynthetic opioids are more of an issue with older people. We saw some noteworthy trends between narcotic-related fatalities and healthcare spending. We observed that increases in the cost of healthcare generally corresponded to increases in the rate of overdoses. On the other hand, the national unemployment rate did not appear to have a signigicant relationship with fatality rates. 

The opioid crisis is an ongoing struggle in our country, increasing in severity dramatically in recent years. In order to fight this issue, it could be helpful to know how different communities are affected, or external societal factors that play a role. Our goal for this project was to show that the data tells a story. Hopefully our findings can contribute to meaningful, lasting solutions. 
