# Interactive graph

<style>
  * {
    font-family: sans-serif;
  }
</style> 

<div id="plot">
</div>

<script src="https://cdn.jsdelivr.net/npm/d3@7"></script>
<script src="scripts/myscript.js"></script>

The interactive plot above provides us with a high level overview of the total national overdose deaths involving any opioid. These numbers are across all races, genders, and ages. Hovering over each bar in the graph displays the specific value of overdose deaths in that specific year. We calculated the total overdose deaths for each year by using the yearly population data from the World Bank and the overdose death rate data from the CDC. Though in previous graphs we have looked at the trends of overdose death rates, we wanted to include a separate graph that quantifies the number of people that have died due to drug overdose. Doing so allows us to understand the severity of the situation and encourages us to take preventative action. We can see from this graph that drug overdose deaths have strictly increased since 1999 to 2017. In the results section of this project, we discussed potential causes for this including the cost increase of private health insurance. We also looked at what demographic groups tend to be the most afflicted. The takeaway from this graph is that drug overdose deaths are increasing, with close to 50,000 people dying from it in 2017. This unfortunate large number informs us of the gravity of the problem and the need to rectify it. 