# Data

## Description

For this project we will be inspecting three separate databases.

### Drug Overdose Death Rates
The first data source we will inspect is called "Drug overdose death rates, by drug type, sex, age, race, and Hispanic origin: United States". This data set shows the rate of overdoses for different age groups, races, and genders from 1999 to 2019. This data set also breaks down the fatalities by drug type. 
These data are collected by the National Center for Health Statistics, which is part of the Centers for Disease Control and Prevention. It is an aggregate of public-use mortality files as well as U.S. Census Bureau national population estimates. 
The data are separated row by row for each demographic, year, and drug type. Each row represents a death rate. For instance, one row tells us that in the year 2017, about 1.6 out of every 100,000 females of American Indian or Alaskan Native descent died to a methodone overdose. 
This database was created in May, 2021 and was last updated in April, 2022. 
There are 6228 rows and 15 columns. 
One issue with this data set is that there are some redundancies. For example, there may be a row on death rates for black males and a separate row for black males (no Hispanic or Latino origin). This issue is easily resolved by faceting the data based on category breakdown. There are several ways to delineate categories, but the "STUB_NAME" column makes it easy to choose which category you would like to inspect (Age, Age and sex, Sex and race and Hispanic origin). By faceting using this column, no redundancies will corrupt the data. 
We accessed this data from the following web page-
https://data.cdc.gov/NCHS/Drug-overdose-death-rates-by-drug-type-sex-age-rac/95ax-ymtc
and downloaded the data set as a CSV file, which we then imported to RStudio. 

### National Health Expenditure Accounts 
The second data source we inspect is called "National Health Expenditures by type of service and source of funds, CY 1960-2021". This comprehensive dataset shows how much money is spent annually on healthcare, both by the government and by the population. It includes dozens of sources, but we are mainly interested in out of pocket, private health insurance, medicare, and medicaid. The purpose for including this data is to create visualizations that show potential relationships between healthcare spending and opioid abuse. Are people in need more likely to self-medicate if the government isn't providing medical care? 
These data are collected by the Centers for Medicare & Medicaid Services. 
The NHEA measures annual U.S. expenditures for health care goods and services, public health activities, government administration, the net cost of health insurance, and investment related to health care. The data are presented by type of service, sources of funding, and type of sponsor.
This dataset is updated annually. 
There are 541 rows and 62 columns. 
An important feature of this data is that the values listed are scaled down 1:1,000,000 so each item must be multiplied by one million to equal its actual value. 
We accessed the data from the following CMS web page-
https://www.cms.gov/data-research/statistics-trends-and-reports/national-health-expenditure-data/historical
and downloaded the data set as a CSV file, which we then imported to RStudio.

### Unemployment Rate
The third and final dataset is the national unemployment rate. This data set consists of a list of years and the corresponding rate of unemployment for each month. 
These data are collected by the U.S. Bureau of Labor Statistics through a nationwide survey for a random sample of the population. 
The database is updated monthly. 
There are 19 rows and 13 columns. 
We accessed this data from the Bureau of Labor Statistics from the following web page- https://data.bls.gov/pdq/SurveyOutputServlet
The website has a handy UI that allows users to select a time frame of years to inspect and download. For our purposes, we selected 1999 to 2017 and exported the data as a XLSX file. The download included some extraneous titles and commends in the XLSX file, so we manually deleted those before importing the numerical data to RStudio. 

## Research Plan
Our data will allow us to explore some of the potential relationships discussed in the introduction. It is well known that correlation does not prove causation, but with well-made graphs we can inspect trends within the data. One question that we asked is "is there a relationship between ethnicity and drug overdose?". To answer this we can facet the overdose dataset by ethnicity and create graphs that display the death rates of different ethnicities next to one another. Another question we asked was "Does an increase in opioid abuse correspond to an increase in the national unemployment rate?". For this, we could superimpose a timeline of the unemployment rate over drug-related mortality rates for working-age groups. Last, we asked "do overdose rates correlate with the cost of healthcare?". To investigate this inquiry, we can use the healthcare spending database to show how much citizens must pay out of pocket for healthcare for a span of years, and compare it to fatal drug-abuse instances. Our general workflow will consist of asking a question, deciding which datasets will help answer that question, parse the datasets to extract relevant information, and finally generate a graph that will let us visualize a trend in the data. 

## Missing value analysis
