# Introduction

Every year about 100,000 people in the United States lose their lives to drug overdose^\[1\]^. The opioid crisis in our country has been a persisting issue for decades. Our goal with this project is to explore trends in opioid-related fatalities over a span of 19 years, from 1999 to 2017. Is ethnicity a major factor in drug overdose rates? What about age or gender? Can we discern which drugs were prevelent in different years? The CDC claims that this crisis has come about as a culmination of three distinct waves. First, in the 1990's, prescription drugs such as painkillers became a prominent issue. Then, around 2010, there was a massive influx in fatal heroin overdoses. Finally, around 2013, deaths due to synthetic opioids such as fentanyl rose tremendously. Does the data provided by the CDC back up these claims? These are a few questions we are interested in answering.

We are also interested in exploring potential correlations with overdoses and other nation-wide trends. Does an increase in opioid abuse correspond to an increase in the national unemployment rate? Do overdose rates correlate with the cost of healthcare? We will explore all of these questions using overdose data from the CDC. We will compare this data to healthcare spending information from the Centers for Medicare and Medicaid services and national unemployment data from the Bureau of Labor Statistics.

\[1\] https://www.cdc.gov/opioids/basics/epidemic.html
